# Generated by Django 5.1.6 on 2025-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todo_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
